export * from './listActions'
export * from './cardActions'

export const CONSTANS = {
   ADD_CARD: 'ADD_CARD',
   ADD_LIST: 'ADD_LIST',
   CHANGE_LIST_TITLE: 'CHANGE_LIST_TITLE',
   DRAG_HAPPEND: 'DRAG_HAPPEND',

   SET_MENU_OPEN: 'SET_MENU_OPEN',
   SET_ICON_VISIBLE: 'SET_ICON_VISIBLE',
   MENU_CLOSE: 'MENU_CLOSE',
   MENU_OPTION_CLICK: 'MENU_OPTION_CLICK',
   SET_INFO_DESCRIPTION: 'SET_INFO_DESCRIPTION,',
   CHANGE_TAG: 'CHANGE_TAG',
   ADD_TAG: 'ADD_TAG',
}